/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2014-12-11 at 22:31:52 UTC 
 * Modify at your own risk.
 */

package com.mycompany.services.pointendpoint;

/**
 * Service definition for Pointendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link PointendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Pointendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the pointendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://androidapp-hesso.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "pointendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Pointendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Pointendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getPoint".
   *
   * This request holds the parameters needed by the pointendpoint server.  After setting any optional
   * parameters, call the {@link GetPoint#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetPoint getPoint(java.lang.Long id) throws java.io.IOException {
    GetPoint result = new GetPoint(id);
    initialize(result);
    return result;
  }

  public class GetPoint extends PointendpointRequest<com.mycompany.services.pointendpoint.model.Point> {

    private static final String REST_PATH = "point/{id}";

    /**
     * Create a request for the method "getPoint".
     *
     * This request holds the parameters needed by the the pointendpoint server.  After setting any
     * optional parameters, call the {@link GetPoint#execute()} method to invoke the remote operation.
     * <p> {@link
     * GetPoint#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetPoint(java.lang.Long id) {
      super(Pointendpoint.this, "GET", REST_PATH, null, com.mycompany.services.pointendpoint.model.Point.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetPoint setAlt(java.lang.String alt) {
      return (GetPoint) super.setAlt(alt);
    }

    @Override
    public GetPoint setFields(java.lang.String fields) {
      return (GetPoint) super.setFields(fields);
    }

    @Override
    public GetPoint setKey(java.lang.String key) {
      return (GetPoint) super.setKey(key);
    }

    @Override
    public GetPoint setOauthToken(java.lang.String oauthToken) {
      return (GetPoint) super.setOauthToken(oauthToken);
    }

    @Override
    public GetPoint setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetPoint) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetPoint setQuotaUser(java.lang.String quotaUser) {
      return (GetPoint) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetPoint setUserIp(java.lang.String userIp) {
      return (GetPoint) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetPoint setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetPoint set(String parameterName, Object value) {
      return (GetPoint) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertPoint".
   *
   * This request holds the parameters needed by the pointendpoint server.  After setting any optional
   * parameters, call the {@link InsertPoint#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.mycompany.services.pointendpoint.model.Point}
   * @return the request
   */
  public InsertPoint insertPoint(com.mycompany.services.pointendpoint.model.Point content) throws java.io.IOException {
    InsertPoint result = new InsertPoint(content);
    initialize(result);
    return result;
  }

  public class InsertPoint extends PointendpointRequest<com.mycompany.services.pointendpoint.model.Point> {

    private static final String REST_PATH = "point";

    /**
     * Create a request for the method "insertPoint".
     *
     * This request holds the parameters needed by the the pointendpoint server.  After setting any
     * optional parameters, call the {@link InsertPoint#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertPoint#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.mycompany.services.pointendpoint.model.Point}
     * @since 1.13
     */
    protected InsertPoint(com.mycompany.services.pointendpoint.model.Point content) {
      super(Pointendpoint.this, "POST", REST_PATH, content, com.mycompany.services.pointendpoint.model.Point.class);
    }

    @Override
    public InsertPoint setAlt(java.lang.String alt) {
      return (InsertPoint) super.setAlt(alt);
    }

    @Override
    public InsertPoint setFields(java.lang.String fields) {
      return (InsertPoint) super.setFields(fields);
    }

    @Override
    public InsertPoint setKey(java.lang.String key) {
      return (InsertPoint) super.setKey(key);
    }

    @Override
    public InsertPoint setOauthToken(java.lang.String oauthToken) {
      return (InsertPoint) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertPoint setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertPoint) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertPoint setQuotaUser(java.lang.String quotaUser) {
      return (InsertPoint) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertPoint setUserIp(java.lang.String userIp) {
      return (InsertPoint) super.setUserIp(userIp);
    }

    @Override
    public InsertPoint set(String parameterName, Object value) {
      return (InsertPoint) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listPoint".
   *
   * This request holds the parameters needed by the pointendpoint server.  After setting any optional
   * parameters, call the {@link ListPoint#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListPoint listPoint() throws java.io.IOException {
    ListPoint result = new ListPoint();
    initialize(result);
    return result;
  }

  public class ListPoint extends PointendpointRequest<com.mycompany.services.pointendpoint.model.CollectionResponsePoint> {

    private static final String REST_PATH = "point";

    /**
     * Create a request for the method "listPoint".
     *
     * This request holds the parameters needed by the the pointendpoint server.  After setting any
     * optional parameters, call the {@link ListPoint#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListPoint#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListPoint() {
      super(Pointendpoint.this, "GET", REST_PATH, null, com.mycompany.services.pointendpoint.model.CollectionResponsePoint.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListPoint setAlt(java.lang.String alt) {
      return (ListPoint) super.setAlt(alt);
    }

    @Override
    public ListPoint setFields(java.lang.String fields) {
      return (ListPoint) super.setFields(fields);
    }

    @Override
    public ListPoint setKey(java.lang.String key) {
      return (ListPoint) super.setKey(key);
    }

    @Override
    public ListPoint setOauthToken(java.lang.String oauthToken) {
      return (ListPoint) super.setOauthToken(oauthToken);
    }

    @Override
    public ListPoint setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListPoint) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListPoint setQuotaUser(java.lang.String quotaUser) {
      return (ListPoint) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListPoint setUserIp(java.lang.String userIp) {
      return (ListPoint) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListPoint setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListPoint setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListPoint set(String parameterName, Object value) {
      return (ListPoint) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removePoint".
   *
   * This request holds the parameters needed by the pointendpoint server.  After setting any optional
   * parameters, call the {@link RemovePoint#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public RemovePoint removePoint(java.lang.Long id) throws java.io.IOException {
    RemovePoint result = new RemovePoint(id);
    initialize(result);
    return result;
  }

  public class RemovePoint extends PointendpointRequest<Void> {

    private static final String REST_PATH = "point/{id}";

    /**
     * Create a request for the method "removePoint".
     *
     * This request holds the parameters needed by the the pointendpoint server.  After setting any
     * optional parameters, call the {@link RemovePoint#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemovePoint#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemovePoint(java.lang.Long id) {
      super(Pointendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemovePoint setAlt(java.lang.String alt) {
      return (RemovePoint) super.setAlt(alt);
    }

    @Override
    public RemovePoint setFields(java.lang.String fields) {
      return (RemovePoint) super.setFields(fields);
    }

    @Override
    public RemovePoint setKey(java.lang.String key) {
      return (RemovePoint) super.setKey(key);
    }

    @Override
    public RemovePoint setOauthToken(java.lang.String oauthToken) {
      return (RemovePoint) super.setOauthToken(oauthToken);
    }

    @Override
    public RemovePoint setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemovePoint) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemovePoint setQuotaUser(java.lang.String quotaUser) {
      return (RemovePoint) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemovePoint setUserIp(java.lang.String userIp) {
      return (RemovePoint) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemovePoint setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemovePoint set(String parameterName, Object value) {
      return (RemovePoint) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updatePoint".
   *
   * This request holds the parameters needed by the pointendpoint server.  After setting any optional
   * parameters, call the {@link UpdatePoint#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.mycompany.services.pointendpoint.model.Point}
   * @return the request
   */
  public UpdatePoint updatePoint(com.mycompany.services.pointendpoint.model.Point content) throws java.io.IOException {
    UpdatePoint result = new UpdatePoint(content);
    initialize(result);
    return result;
  }

  public class UpdatePoint extends PointendpointRequest<com.mycompany.services.pointendpoint.model.Point> {

    private static final String REST_PATH = "point";

    /**
     * Create a request for the method "updatePoint".
     *
     * This request holds the parameters needed by the the pointendpoint server.  After setting any
     * optional parameters, call the {@link UpdatePoint#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdatePoint#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.mycompany.services.pointendpoint.model.Point}
     * @since 1.13
     */
    protected UpdatePoint(com.mycompany.services.pointendpoint.model.Point content) {
      super(Pointendpoint.this, "PUT", REST_PATH, content, com.mycompany.services.pointendpoint.model.Point.class);
    }

    @Override
    public UpdatePoint setAlt(java.lang.String alt) {
      return (UpdatePoint) super.setAlt(alt);
    }

    @Override
    public UpdatePoint setFields(java.lang.String fields) {
      return (UpdatePoint) super.setFields(fields);
    }

    @Override
    public UpdatePoint setKey(java.lang.String key) {
      return (UpdatePoint) super.setKey(key);
    }

    @Override
    public UpdatePoint setOauthToken(java.lang.String oauthToken) {
      return (UpdatePoint) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdatePoint setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdatePoint) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdatePoint setQuotaUser(java.lang.String quotaUser) {
      return (UpdatePoint) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdatePoint setUserIp(java.lang.String userIp) {
      return (UpdatePoint) super.setUserIp(userIp);
    }

    @Override
    public UpdatePoint set(String parameterName, Object value) {
      return (UpdatePoint) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Pointendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Pointendpoint}. */
    @Override
    public Pointendpoint build() {
      return new Pointendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link PointendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setPointendpointRequestInitializer(
        PointendpointRequestInitializer pointendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(pointendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
